# Generated by Django 5.0.6 on 2024-08-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_qty', models.IntegerField()),
                ('buyer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_qty', models.IntegerField()),
            ],
        ),
    ]
